# Generated by Django 2.2.1 on 2019-05-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightclasses',
            name='id',
        ),
        migrations.AlterField(
            model_name='weightclasses',
            name='weight_class_text',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
