# Generated by Django 2.2.1 on 2019-05-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0002_auto_20190529_0323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeightClasses',
            new_name='WeightClass',
        ),
    ]
