# Generated by Django 2.2.1 on 2019-05-29 04:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0004_airportclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasdaqIndexClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=8)),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='created')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated')),
                ('weight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exoapp.WeightClass')),
            ],
        ),
    ]
