# Generated by Django 2.2.1 on 2019-05-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0005_nasdaqindexclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='nasdaqindexclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
