# Generated by Django 2.2.1 on 2019-05-31 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0007_auto_20190529_0550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NasdaqIndexClass',
            new_name='NasdaqIndex',
        ),
    ]
