# Generated by Django 2.2.1 on 2019-05-31 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0008_auto_20190531_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nasdaqindex',
            name='standard_deviation',
        ),
        migrations.RemoveField(
            model_name='nasdaqindex',
            name='volume',
        ),
    ]
