# Generated by Django 2.2.1 on 2019-05-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0009_auto_20190531_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasdaqindex',
            name='weight_class',
            field=models.CharField(max_length=8),
        ),
    ]
