# Generated by Django 2.2.1 on 2019-05-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0012_auto_20190531_0509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightclass',
            old_name='weight_class_text',
            new_name='weight_class',
        ),
    ]
