# Generated by Django 2.2.1 on 2019-05-31 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0014_auto_20190531_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='NasdaqAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=8)),
                ('price_average', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='created')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated')),
            ],
        ),
    ]
