# Generated by Django 2.2.1 on 2019-06-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0015_nasdaqaverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportclass',
            name='class_1',
            field=models.IntegerField(blank=True, default=None, help_text='First internal classification.', null=True),
        ),
        migrations.AddField(
            model_name='airportclass',
            name='class_2',
            field=models.IntegerField(blank=True, default=None, help_text='Second internal classification.', null=True),
        ),
        migrations.AddField(
            model_name='airportclass',
            name='continent',
            field=models.CharField(blank=True, default=None, help_text='The continent the airport is on.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airportclass',
            name='iso_country',
            field=models.CharField(blank=True, default=None, help_text='Official country code of the airport.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airportclass',
            name='iso_region',
            field=models.CharField(blank=True, default=None, help_text='Official region code of the airport.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airportclass',
            name='latitude_deg',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='airportclass',
            name='longitude_deg',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='airportclass',
            name='municipality',
            field=models.CharField(blank=True, default=None, help_text='The municipality the airport is located in.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airportclass',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='Official name of the airport', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airportclass',
            name='type',
            field=models.CharField(blank=True, default=None, help_text='Official type (size) of airport.', max_length=50, null=True),
        ),
    ]
