# Generated by Django 2.2.1 on 2019-06-06 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0017_auto_20190606_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportclass',
            name='iso_country',
            field=models.ForeignKey(blank=True, default=None, help_text='Official country code of the airport.', null=True, on_delete=django.db.models.deletion.CASCADE, to='exoapp.Country'),
        ),
    ]
