# Generated by Django 2.2.1 on 2019-06-06 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0018_auto_20190606_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('base_order_date', models.DateField(blank=True, default=None, help_text='The date the base order was established (or last revised).', null=True)),
                ('target_period', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='created')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated')),
            ],
        ),
    ]
