# Generated by Django 2.2.1 on 2019-06-06 01:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0020_baseorderlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('order_date', models.DateField(blank=True, default=None, help_text='The date the order was established (or last revised).', null=True)),
                ('target_week', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='created')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated')),
            ],
        ),
        migrations.RenameModel(
            old_name='AirportClass',
            new_name='Airport',
        ),
        migrations.RenameModel(
            old_name='BaseOrderLines',
            new_name='BaseOrderLine',
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('etd', models.DateField(blank=True, default=None, null=True)),
                ('target_arrival', models.DateField(blank=True, default=None, null=True)),
                ('estimated_arrival', models.DateField(blank=True, default=None, null=True)),
                ('actual_arrival', models.DateField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='created')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated')),
                ('order_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exoapp.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(blank=True, default=None, help_text='The base order volume (in boxes) for the given `weight_class`.', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='created')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated')),
                ('shipment_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exoapp.Order')),
                ('weight_class', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exoapp.WeightClass')),
            ],
        ),
    ]
