# Generated by Django 2.2.1 on 2019-06-06 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0023_auto_20190606_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='shipment_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exoapp.Shipment'),
        ),
    ]
