# Generated by Django 2.2.1 on 2019-06-06 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0027_shipment_departure_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdestination',
            name='latitude_deg',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='customerdestination',
            name='longitude_deg',
            field=models.DecimalField(blank=True, decimal_places=10, default=None, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='customerdestinationairport',
            name='distance',
            field=models.IntegerField(blank=True, default=None, help_text='Driving distance in km to shipment address.', null=True),
        ),
    ]
