# Generated by Django 2.2.1 on 2019-06-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0029_customerpricetarget_destinationcost_destinationpricetarget_quote_quoteline_quotevalidity_weekcosttar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseorder',
            old_name='customer_destination_airport_id',
            new_name='customer_destination_id',
        ),
    ]
