# Generated by Django 2.2.1 on 2019-06-06 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0031_auto_20190606_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerShipmentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(blank=True, default=None, help_text='The order line volume (in boxes) for the given `weight_class`.', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='created')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, default=None, help_text='The timespan the quote is valid.', null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='created')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated')),
                ('quote_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exoapp.Quote')),
            ],
        ),
        migrations.RemoveField(
            model_name='shipmentline',
            name='shipment_id',
        ),
        migrations.RemoveField(
            model_name='shipmentline',
            name='weight_class',
        ),
        migrations.RenameField(
            model_name='customershipment',
            old_name='etd',
            new_name='estimated_departure',
        ),
        migrations.DeleteModel(
            name='QuoteValidity',
        ),
        migrations.DeleteModel(
            name='ShipmentLine',
        ),
        migrations.AddField(
            model_name='customershipmentline',
            name='customer_shipment_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exoapp.CustomerShipment'),
        ),
        migrations.AddField(
            model_name='customershipmentline',
            name='weight_class',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exoapp.WeightClass'),
        ),
    ]
