# Generated by Django 2.2.1 on 2019-06-06 09:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0032_auto_20190606_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuoteLine',
            new_name='PriceQuoteLine',
        ),
        migrations.AddField(
            model_name='quote',
            name='result_code',
            field=models.CharField(blank=True, default=None, help_text='An internal classification of the result of the quote process.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='VolumeQuoteLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('class_1', models.IntegerField(blank=True, default=None, help_text='Quote or counteroffer (ask).', null=True)),
                ('status', models.IntegerField(blank=True, default=None, help_text='Internal grading until closed.', null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='created')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='updated')),
                ('quote_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exoapp.Quote')),
                ('weight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exoapp.WeightClass')),
            ],
        ),
    ]
