# Generated by Django 2.2.1 on 2019-06-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoapp', '0033_auto_20190606_0905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VolumeQuoteLine',
            new_name='VolumePipeLine',
        ),
    ]
